version: 2.1

jobs:
  build0:
    docker:
      - image: cyversevice/rstudio-geospatial:latest
    steps:
      - checkout
      - run: rstudio-server version
  build1:
    docker:
      - image: cyversevice/rstudio-geospatial:4.0.0-ubuntu18.04
    steps:
      - checkout
      - run: rstudio-server version
  build2:
    docker:
      - image: cyversevice/rstudio-geospatial:3.6.3
    steps:
      - checkout
      - run: rstudio-server version

workflows:
  build:
    jobs:
      - build0
      - build1
      - build2
